add error handling

diff --git a/.github/workflows/asana.yml b/.github/workflows/asana.yml
--- a/.github/workflows/asana.yml
+++ b/.github/workflows/asana.yml
@@ -27,10 +27,14 @@ jobs:
           # that is: https://app.asana.com/0/<projectID>/<taskId>
           # TODO: add support for multiple tasks in the same PR description
           ASANA_TASK_ID=$(echo "${PR_DESCRIPTION}" | grep ${{ env.ASANA_APP_URL }} | awk -F"/" '{print $NF}')
-          echo "Updating task with id ${ASANA_TASK_ID} to In Staging"
+          echo "Updating task with id ${ASANA_TASK_ID} to section: In Staging"
           curl -s --request POST \
                --url ${{ env.ASANA_APP_URL }}/api/1.0/sections/${{ env.ASANA_GOPHERS_SECTION_IN_STAGING }}/addTask \
                --header 'accept: application/json' \
                --header 'authorization: Bearer '${{ secrets.ASANA_TOKEN }} \
                --header 'content-type: application/json' \
-               --data '{ "data": {"task": "'${ASANA_TASK_ID}'"} }'
+               --data '{ "data": {"task": "'${ASANA_TASK_ID}'"} }' || {
+                 echo "error updating task with id ${ASANA_TASK_ID}"
+                 return 1
+               }
+           echo "Successfully updated task with id ${ASANA_TASK_ID}"
